/*
 * Look4Sat. Amateur radio satellite tracker and pass predictor.
 * Copyright (C) 2019-2026 Arty Bishop and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.rtbishop.look4sat.feature.map

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import org.json.JSONObject
import org.osmdroid.views.MapView
import org.osmdroid.views.Projection
import org.osmdroid.views.overlay.Overlay
import java.io.InputStream
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

/**
 * One administrative/boundary region loaded from the award GeoJSON assets.
 *
 * @param code     match key against award statistics (e.g. "GD", "34", "24", "CA", "318")
 * @param name     display label (province/prefecture/state/country name)
 * @param labelLon/labelLat preferred label anchor (usually the region centroid)
 * @param rings    polygon exterior rings as lon/lat pairs; the overlay projects
 *                 them per frame with the same projection helpers as the grid overlay
 */
data class AwardRegion(
    val code: String,
    val name: String,
    val labelLon: Double,
    val labelLat: Double,
    val rings: List<List<DoubleArray>>,
    val forceLabel: Boolean = false
)

/**
 * Loads and caches the award boundary assets (assets/awards/<type>.json).
 * Format (generated by the awarddata/convert2.py pipeline):
 *   {"type": "wapc", "regions": [{"id":..,"code":"GD","name":"广东省",
 *     "label_lon":..,"label_lat":..,"rings":[[[lon,lat],...],...]}, ...]}
 */
object AwardBoundaryData {

    private val cache = mutableMapOf<AwardAsset, List<AwardRegion>>()

    enum class AwardAsset(val fileName: String) {
        WAPC("wapc.json"),
        WAJA("waja.json"),
        WAZ("waz.json"),
        WAS("was.json"),
        DXCC("dxcc.json")
    }

    fun load(context: Context, asset: AwardAsset): List<AwardRegion> {
        cache[asset]?.let { return it }
        val regions = try {
            val stream: InputStream = context.assets.open("awards/${asset.fileName}")
            val text = stream.bufferedReader().use { it.readText() }
            val root = JSONObject(text)
            val array = root.optJSONArray("regions") ?: return emptyList()
            val list = mutableListOf<AwardRegion>()
            for (i in 0 until array.length()) {
                val o = array.optJSONObject(i) ?: continue
                val ringsArray = o.optJSONArray("rings") ?: continue
                val rings = mutableListOf<List<DoubleArray>>()
                for (r in 0 until ringsArray.length()) {
                    val ring = ringsArray.optJSONArray(r) ?: continue
                    val points = mutableListOf<DoubleArray>()
                    for (p in 0 until ring.length()) {
                        val pt = ring.optJSONArray(p) ?: continue
                        if (pt.length() >= 2) points.add(doubleArrayOf(pt.getDouble(0), pt.getDouble(1)))
                    }
                    if (points.size >= 3) rings.add(points)
                }
                if (rings.isEmpty()) continue
                list.add(
                    AwardRegion(
                        code = o.optString("code"),
                        name = o.optString("name"),
                        labelLon = o.optDouble("label_lon", 0.0),
                        labelLat = o.optDouble("label_lat", 0.0),
                        rings = rings,
                        forceLabel = o.optBoolean("force_label", false)
                    )
                )
            }
            list
        } catch (_: Exception) {
            emptyList()
        }
        cache[asset] = regions
        return regions
    }
}

/**
 * Renders award boundary regions (provinces/prefectures/CQ zones/states/
 * countries) with the same visual language as the VUCC grid overlay:
 * yellow boundary lines, green fill for worked regions, yellow labels.
 *
 * Worked regions are matched by [workedCodes] against each region's [AwardRegion.code]
 * (e.g. {"GD", "ZJ", "HK", ...} for WAPC). All region boundaries are always drawn
 * so missing regions stay visible; only worked ones get the green fill.
 */
class AwardBoundaryOverlay : Overlay() {

    private val linePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        strokeWidth = 1.5f
        style = Paint.Style.STROKE
        color = Color.argb(160, 255, 224, 130)
    }
    private val labelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        textSize = 22f
        style = Paint.Style.FILL
        color = Color.argb(220, 255, 224, 130)
        setShadowLayer(3f, 2f, 2f, Color.BLACK)
    }
    private val workedPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        style = Paint.Style.FILL
        color = Color.argb(90, 76, 217, 100)
    }

    /** Boundary regions to render; assigning recomputes culling bounds. */
    var regions: List<AwardRegion> = emptyList()
        set(value) {
            field = value
            regionBounds.clear()
            for (r in value) {
                var minLon = Double.MAX_VALUE; var minLat = Double.MAX_VALUE
                var maxLon = -Double.MAX_VALUE; var maxLat = -Double.MAX_VALUE
                for (ring in r.rings) for (pt in ring) {
                    if (pt[0] < minLon) minLon = pt[0]
                    if (pt[0] > maxLon) maxLon = pt[0]
                    if (pt[1] < minLat) minLat = pt[1]
                    if (pt[1] > maxLat) maxLat = pt[1]
                }
                regionBounds.add(doubleArrayOf(minLon, minLat, maxLon, maxLat))
            }
        }

    /** Codes of worked regions -> green fill. */
    var workedCodes: Set<String> = emptySet()

    /** Bounding boxes (computed on region assignment) for cheap culling. */
    private val regionBounds = mutableListOf<DoubleArray>() // [minLon,minLat,maxLon,maxLat]

    override fun setEnabled(on: Boolean) {
        super.setEnabled(on)
    }

    override fun draw(canvas: Canvas, mapView: MapView, shadow: Boolean) {
        if (shadow || !isEnabled || regions.isEmpty()) return
        val projection = mapView.projection
        val zoom = mapView.zoomLevelDouble
        val worldWidthPx = 256.0 * Math.pow(2.0, zoom)

        // Visible bounding box (same anchor-on-center approach as the grid overlay).
        val north = projection.fromPixels(0, 0)
        val south = projection.fromPixels(canvas.width, canvas.height)
        val topLat = max(north.latitude, south.latitude).coerceIn(-90.0, 90.0)
        val bottomLat = min(north.latitude, south.latitude).coerceIn(-90.0, 90.0)
        val viewCenter = projection.fromPixels(canvas.width / 2, canvas.height / 2)
        val centerLon = viewCenter.longitude
        val halfSpanDeg = (canvas.width / 2.0) / worldWidthPx * 360.0
        val leftLon = centerLon - halfSpanDeg
        val rightLon = centerLon + halfSpanDeg

        labelPaint.textAlign = Paint.Align.CENTER
        val fontMetrics = labelPaint.fontMetrics
        val textHalfHeight = (fontMetrics.descent + fontMetrics.ascent) / 2f

        for (i in regions.indices) {
            val region = regions[i]
            val b = regionBounds.getOrNull(i) ?: continue
            // Cull: region bbox outside the visible span (with wrap slack).
            if (b[1] > topLat || b[3] < bottomLat) continue
            if (b[0] > rightLon || b[2] < leftLon) continue
            val worked = region.code in workedCodes

            val path = Path()
            var pathHasPoints = false
            for (ring in region.rings) {
                // Split each ring into consecutive segments at the antimeridian
                // (±180°) and draw each as its own sub-path. Naively normalizing
                // every vertex to [-180,180) folds vertices that sit on the
                // "far" side of ±180 onto the opposite screen edge, drawing a
                // spurious line that sweeps across the whole map (Russia/Fiji/
                // Antarctica for DXCC, the Pacific CQ zones for WAZ). Splitting
                // keeps each segment contiguous. Each segment then gets ONE
                // per-segment longitude offset (in whole 360° turns) chosen to
                // sit closest to the view center, so vertices far from the
                // center are not folded to ±180 the wrong way at low zoom.
                // A ring that was NOT split keeps implicit closure (close());
                // a SPLIT ring must NOT be closed per segment — each close()
                // would draw a straight chord across the map between the two
                // cut ends (visible as a bogus Russia border line), so the
                // cut edges are left open.
                val segments = splitRingAtAntimeridian(ring)
                val closeRing = segments.size == 1
                for (segment in segments) {
                    if (segment.isEmpty()) continue
                    pathHasPoints = traceSegment(path, segment, projection, centerLon, worldWidthPx, closeRing) || pathHasPoints
                }
            }
            if (!pathHasPoints) continue

            if (worked) canvas.drawPath(path, workedPaint)
            canvas.drawPath(path, linePaint)

            // Label: draw when its anchor is on screen and the region is big
            // enough on screen to hold the text (avoid clutter at low zoom).
            val labelLonNorm = normalizeLon(region.labelLon)
            if (labelLonNorm < leftLon - 1.0 || labelLonNorm > rightLon + 1.0) continue
            if (region.labelLat < bottomLat - 1.0 || region.labelLat > topLat + 1.0) continue
            val lx = projectionToX(projection, labelLonNorm, centerLon, worldWidthPx) ?: continue
            val ly = projectionToY(projection, region.labelLat) ?: continue
            // Screen-size gate: the label only when the region spans enough px.
            // force_label regions (HK / Macau) always draw — their tiny land
            // bbox would otherwise stay below the gate forever, and their label
            // anchor sits out on the sea where there is room for the text.
            val regionH = (projectionToY(projection, b[3]) ?: 0f) - (projectionToY(projection, b[1]) ?: 0f)
            if (abs(regionH) < MIN_LABEL_REGION_PX && !region.forceLabel) continue
            canvas.drawText(region.name, lx, ly - textHalfHeight, labelPaint)
        }
    }

    /**
     * Splits a ring's vertices into consecutive segments that do NOT cross the
     * antimeridian. Vertices are first normalized to [-180,180); whenever two
     * consecutive vertices differ by more than 180° in longitude (the ring
     * wraps over ±180), the segment is closed there and a new segment starts.
     *
     * A ring that crosses the antimeridian (e.g. Russia's eastern tip, or the
     * Pacific CQ zones whose raw lon runs past ±180) becomes two segments, each
     * kept geometrically contiguous so no spurious long edge is drawn.
     */
    private fun splitRingAtAntimeridian(ring: List<DoubleArray>): List<List<DoubleArray>> {
        val n = ring.size
        if (n == 0) return emptyList()
        val pts = Array(n) { doubleArrayOf(normalizeLon(ring[it][0]), ring[it][1]) }
        val segments = mutableListOf<MutableList<DoubleArray>>()
        var cur = mutableListOf<DoubleArray>()
        cur.add(pts[0])
        for (i in 1 until n) {
            val prevLon = pts[i - 1][0]
            val lon = pts[i][0]
            if (abs(lon - prevLon) > 180.0) {
                // Crossed the antimeridian: start a fresh segment.
                if (cur.size >= 2) segments.add(cur)
                cur = mutableListOf()
            }
            cur.add(pts[i])
        }
        if (cur.size >= 2) segments.add(cur)
        // A fully-winding ring may have collapsed into a single segment after
        // normalization (no actual crossing between consecutive vertices); in
        // that case fall back to the whole ring as one segment.
        if (segments.isEmpty()) segments.add(mutableListOf<DoubleArray>().also { it.addAll(pts) })
        return segments
    }

    /**
     * Projects [segment] into [path], keeping the segment's geometry
     * contiguous on screen.
     *
     * Longitudes are normalized once when the ring is split, and every vertex
     * of a segment lies within 180° of its neighbours (a segment never crosses
     * the antimeridian). We anchor on the segment's FIRST vertex: its screen x
     * comes from [projectionToX] (correctly placed relative to the view
     * center), and every other vertex is offset by the *continuous* longitude
     * difference from that anchor, scaled by worldWidthPx. Because the whole
     * segment stays on the "near" side of ±180 relative to its anchor, no
     * vertex is folded to the opposite screen edge — that fold is what drew
     * the spurious long lines across the map (Russia/Fiji/Antarctica for
     * DXCC, the Pacific CQ zones for WAZ).
     *
     * @return true if at least one point was placed in the path
     */
    private fun traceSegment(
        path: Path,
        segment: List<DoubleArray>,
        projection: Projection,
        centerLon: Double,
        worldWidthPx: Double,
        closeRing: Boolean
    ): Boolean {
        if (segment.isEmpty()) return false
        val anchorLon = segment[0][0]
        val anchorX = projectionToX(projection, anchorLon, centerLon, worldWidthPx) ?: return false
        var penDown = false
        var any = false
        for (i in segment.indices) {
            val pt = segment[i]
            // Continuous longitude difference from the anchor — no per-vertex
            // fold. For ordinary segments (span < 180° after the antimeridian
            // split) the raw delta is already correct. For full-circle rings
            // (e.g. Antarctica, which runs from -180° eastward to +178° and
            // relies on close() to seal a ~1.7° gap at the antimeridian) the
            // raw delta approaches ±360°, which threw the path a full world
            // turn off-screen and drew a spurious line across the map. Normal
            //ising to [-180,180] keeps every vertex on the nearest turn.
            val delta = normalizeLon(pt[0] - anchorLon)
            val x = anchorX + (delta / 360.0 * worldWidthPx).toFloat()
            val y = projectionToY(projection, pt[1]) ?: continue
            if (!penDown) {
                path.moveTo(x, y)
                penDown = true
            } else {
                path.lineTo(x, y)
            }
            any = true
        }
        if (penDown && closeRing) path.close()
        return any
    }

    /** X pixel for a longitude (Mercator X is linear in longitude). */
    private fun projectionToX(projection: Projection, lon: Double, centerLon: Double, worldWidthPx: Double): Float? {
        var delta = lon - centerLon
        while (delta > 180.0) delta -= 360.0
        while (delta < -180.0) delta += 360.0
        val geo = org.osmdroid.util.GeoPoint(0.0, centerLon)
        val p = projection.toPixels(geo, null)
        return (p.x + delta / 360.0 * worldWidthPx).toFloat()
    }

    /** Y pixel for a latitude. */
    private fun projectionToY(projection: Projection, lat: Double): Float? {
        val geo = org.osmdroid.util.GeoPoint(lat, 0.0)
        val p = projection.toPixels(geo, null)
        return p.y.toFloat()
    }

    private fun normalizeLon(lon: Double): Double {
        var l = lon % 360.0
        if (l >= 180.0) l -= 360.0
        if (l < -180.0) l += 360.0
        return l
    }

    private companion object {
        const val MIN_LABEL_REGION_PX = 42f
    }
}
