/*
 * Look4Sat. Amateur radio satellite tracker and pass predictor.
 * Copyright (C) 2019-2026 Arty Bishop and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.rtbishop.look4sat.feature.map

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import org.json.JSONObject
import org.osmdroid.views.MapView
import org.osmdroid.views.Projection
import org.osmdroid.views.overlay.Overlay
import java.io.InputStream
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

/**
 * One administrative/boundary region loaded from the award GeoJSON assets.
 *
 * @param code     match key against award statistics (e.g. "GD", "34", "24", "CA", "318")
 * @param name     display label (province/prefecture/state/country name)
 * @param labelLon/labelLat preferred label anchor (usually the region centroid)
 * @param rings    polygon exterior rings as lon/lat pairs; the overlay projects
 *                 them per frame with the same projection helpers as the grid overlay
 */
data class AwardRegion(
    val code: String,
    val name: String,
    val labelLon: Double,
    val labelLat: Double,
    val rings: List<List<DoubleArray>>
)

/**
 * Loads and caches the award boundary assets (assets/awards/<type>.json).
 * Format (generated by the awarddata/convert2.py pipeline):
 *   {"type": "wapc", "regions": [{"id":..,"code":"GD","name":"广东省",
 *     "label_lon":..,"label_lat":..,"rings":[[[lon,lat],...],...]}, ...]}
 */
object AwardBoundaryData {

    private val cache = mutableMapOf<AwardAsset, List<AwardRegion>>()

    enum class AwardAsset(val fileName: String) {
        WAPC("wapc.json"),
        WAJA("waja.json"),
        WAZ("waz.json"),
        WAS("was.json"),
        DXCC("dxcc.json")
    }

    fun load(context: Context, asset: AwardAsset): List<AwardRegion> {
        cache[asset]?.let { return it }
        val regions = try {
            val stream: InputStream = context.assets.open("awards/${asset.fileName}")
            val text = stream.bufferedReader().use { it.readText() }
            val root = JSONObject(text)
            val array = root.optJSONArray("regions") ?: return emptyList()
            val list = mutableListOf<AwardRegion>()
            for (i in 0 until array.length()) {
                val o = array.optJSONObject(i) ?: continue
                val ringsArray = o.optJSONArray("rings") ?: continue
                val rings = mutableListOf<List<DoubleArray>>()
                for (r in 0 until ringsArray.length()) {
                    val ring = ringsArray.optJSONArray(r) ?: continue
                    val points = mutableListOf<DoubleArray>()
                    for (p in 0 until ring.length()) {
                        val pt = ring.optJSONArray(p) ?: continue
                        if (pt.length() >= 2) points.add(doubleArrayOf(pt.getDouble(0), pt.getDouble(1)))
                    }
                    if (points.size >= 3) rings.add(points)
                }
                if (rings.isEmpty()) continue
                list.add(
                    AwardRegion(
                        code = o.optString("code"),
                        name = o.optString("name"),
                        labelLon = o.optDouble("label_lon", 0.0),
                        labelLat = o.optDouble("label_lat", 0.0),
                        rings = rings
                    )
                )
            }
            list
        } catch (_: Exception) {
            emptyList()
        }
        cache[asset] = regions
        return regions
    }
}

/**
 * Renders award boundary regions (provinces/prefectures/CQ zones/states/
 * countries) with the same visual language as the VUCC grid overlay:
 * yellow boundary lines, green fill for worked regions, yellow labels.
 *
 * Worked regions are matched by [workedCodes] against each region's [AwardRegion.code]
 * (e.g. {"GD", "ZJ", "HK", ...} for WAPC). All region boundaries are always drawn
 * so missing regions stay visible; only worked ones get the green fill.
 */
class AwardBoundaryOverlay : Overlay() {

    private val linePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        strokeWidth = 1.5f
        style = Paint.Style.STROKE
        color = Color.argb(160, 255, 224, 130)
    }
    private val labelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        textSize = 22f
        style = Paint.Style.FILL
        color = Color.argb(220, 255, 224, 130)
        setShadowLayer(3f, 2f, 2f, Color.BLACK)
    }
    private val workedPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        style = Paint.Style.FILL
        color = Color.argb(90, 76, 217, 100)
    }

    /** Boundary regions to render; assigning recomputes culling bounds. */
    var regions: List<AwardRegion> = emptyList()
        set(value) {
            field = value
            regionBounds.clear()
            for (r in value) {
                var minLon = Double.MAX_VALUE; var minLat = Double.MAX_VALUE
                var maxLon = -Double.MAX_VALUE; var maxLat = -Double.MAX_VALUE
                for (ring in r.rings) for (pt in ring) {
                    if (pt[0] < minLon) minLon = pt[0]
                    if (pt[0] > maxLon) maxLon = pt[0]
                    if (pt[1] < minLat) minLat = pt[1]
                    if (pt[1] > maxLat) maxLat = pt[1]
                }
                regionBounds.add(doubleArrayOf(minLon, minLat, maxLon, maxLat))
            }
        }

    /** Codes of worked regions -> green fill. */
    var workedCodes: Set<String> = emptySet()

    /** Bounding boxes (computed on region assignment) for cheap culling. */
    private val regionBounds = mutableListOf<DoubleArray>() // [minLon,minLat,maxLon,maxLat]

    private var canvasWidthPx = 1080f

    override fun setEnabled(on: Boolean) {
        super.setEnabled(on)
    }

    override fun draw(canvas: Canvas, mapView: MapView, shadow: Boolean) {
        if (shadow || !isEnabled || regions.isEmpty()) return
        val projection = mapView.projection
        val zoom = mapView.zoomLevelDouble
        canvasWidthPx = canvas.width.toFloat()
        val worldWidthPx = 256.0 * Math.pow(2.0, zoom)

        // Visible bounding box (same anchor-on-center approach as the grid overlay).
        val north = projection.fromPixels(0, 0)
        val south = projection.fromPixels(canvas.width, canvas.height)
        val topLat = max(north.latitude, south.latitude).coerceIn(-90.0, 90.0)
        val bottomLat = min(north.latitude, south.latitude).coerceIn(-90.0, 90.0)
        val viewCenter = projection.fromPixels(canvas.width / 2, canvas.height / 2)
        val centerLon = viewCenter.longitude
        val halfSpanDeg = (canvas.width / 2.0) / worldWidthPx * 360.0
        val leftLon = centerLon - halfSpanDeg
        val rightLon = centerLon + halfSpanDeg

        labelPaint.textAlign = Paint.Align.CENTER
        val fontMetrics = labelPaint.fontMetrics
        val textHalfHeight = (fontMetrics.descent + fontMetrics.ascent) / 2f

        for (i in regions.indices) {
            val region = regions[i]
            val b = regionBounds.getOrNull(i) ?: continue
            // Cull: region bbox outside the visible span (with wrap slack).
            if (b[1] > topLat || b[3] < bottomLat) continue
            if (b[0] > rightLon || b[2] < leftLon) continue
            val worked = region.code in workedCodes

            val path = Path()
            var pathHasPoints = false
            for (ring in region.rings) {
                var penDown = false
                var prevX = 0f
                var prevY = 0f
                var lastLon = Double.NaN
                for (pt in ring) {
                    val lon = pt[0]
                    val lat = pt[1]
                    // Split rings crossing the antimeridian (|dLon| > 180°).
                    if (penDown && !lastLon.isNaN() && abs(lon - lastLon) > 180.0) {
                        penDown = false
                    }
                    val x = projectionToX(projection, lon, centerLon, worldWidthPx) ?: continue
                    val y = projectionToY(projection, lat) ?: continue
                    if (!penDown) {
                        path.moveTo(x, y)
                        penDown = true
                    } else {
                        path.lineTo(x, y)
                    }
                    prevX = x; prevY = y; lastLon = lon
                    pathHasPoints = true
                }
                if (penDown) path.close()
            }
            if (!pathHasPoints) continue

            if (worked) canvas.drawPath(path, workedPaint)
            canvas.drawPath(path, linePaint)

            // Label: draw when its anchor is on screen and the region is big
            // enough on screen to hold the text (avoid clutter at low zoom).
            val labelLonNorm = normalizeLon(region.labelLon)
            if (labelLonNorm < leftLon - 1.0 || labelLonNorm > rightLon + 1.0) continue
            if (region.labelLat < bottomLat - 1.0 || region.labelLat > topLat + 1.0) continue
            val lx = projectionToX(projection, labelLonNorm, centerLon, worldWidthPx) ?: continue
            val ly = projectionToY(projection, region.labelLat) ?: continue
            // Screen-size gate: the label only when the region spans enough px.
            val regionH = (projectionToY(projection, b[3]) ?: 0f) - (projectionToY(projection, b[1]) ?: 0f)
            if (abs(regionH) < MIN_LABEL_REGION_PX) continue
            canvas.drawText(region.name, lx, ly - textHalfHeight, labelPaint)
        }
    }

    /** X pixel for a longitude (Mercator X is linear in longitude). */
    private fun projectionToX(projection: Projection, lon: Double, centerLon: Double, worldWidthPx: Double): Float? {
        var delta = lon - centerLon
        while (delta > 180.0) delta -= 360.0
        while (delta < -180.0) delta += 360.0
        val geo = org.osmdroid.util.GeoPoint(0.0, centerLon)
        val p = projection.toPixels(geo, null)
        return (p.x + delta / 360.0 * worldWidthPx).toFloat()
    }

    /** Y pixel for a latitude. */
    private fun projectionToY(projection: Projection, lat: Double): Float? {
        val geo = org.osmdroid.util.GeoPoint(lat, 0.0)
        val p = projection.toPixels(geo, null)
        return p.y.toFloat()
    }

    private fun normalizeLon(lon: Double): Double {
        var l = lon % 360.0
        if (l >= 180.0) l -= 360.0
        if (l < -180.0) l += 360.0
        return l
    }

    private companion object {
        const val MIN_LABEL_REGION_PX = 42f
    }
}
